version: "3"
services:
  dev:
    build:
      context: .
    hostname: worker_1
    entrypoint: celery
    command: -A workerA worker --loglevel=debug
    volumes:
      - .:/app
    links:
      - rabbit
    depends_on:
      - rabbit
