- hosts: all
  
  tasks:
   
   - name: Generate hosts file
     lineinfile: dest=/etc/hosts
                 regexp='.*{{ item }}$'
                 line="{{ hostvars[item].ansible_default_ipv4.address }} {{item}}"
                 state=present            
     when: hostvars[item].ansible_default_ipv4.address is defined
     with_items: "{{groups['all']}}"
     become: true
     
   - name: Set hostname
     hostname: name="{{inventory_hostname}}"
     become: true

   - name: apt update
     apt: update_cache=yes upgrade=dist
     become: true

   - name: Download git repository
     become: true
     git:
      repo: 'https://github.com/resa-git/model_serving.git'
      dest: /model_serving
      accept_hostkey: yes
      force: yes
      
   - name: Change ownership of a directory
     become: true
     file:
      path: /technical-training
      state: directory
      recurse: yes
      owner: appuser
      group: appuser

- hosts: devserver
  
  tasks:
    - name: Generate SSH keys
      shell: ssh-keygen -b 2048 -f /home/appuser/.ssh/id_rsa -t rsa -q -N ""
      args:
        creates: /home/appuser/.ssh/id_rsa
    - name: Copy Public Key Locally
      fetch:
        src: /home/appuser/.ssh/id_rsa.pub
        dest: /tmp/
        flat: yes

- hosts: prodserver
 
  vars_files:
   - setup_var.yml  
  
  tasks:  
   - name: Extra packages
     apt: pkg={{item}} state=latest update_cache=true 
     with_items:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
     become: true  

   - name: apt update
     apt: update_cache=yes upgrade=dist
     become: true

   - name: Add Docker repository key
     apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present
     become: true

   - name: Add Docker repository 
     command: add-apt-repository -y "deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable"
     become: true

   - name: apt update
     apt: update_cache=yes upgrade=dist
     become: true

   - name: Append Public key in authorized_keys file
     authorized_key:
       user: appuser
       state: present
       key: "{{ lookup('file', '/tmp/id_rsa.pub') }}"

   - name: Create git jump directory
     file:
       path: /home/appuser/jump
       state: directory

   - name: Change cd to my_project and initialze empty git repo
     command: chdir=/home/appuser/jump git init --bare

   - name: Copy file with owner and permissions
     ansible.builtin.copy:
       src: /home/ubuntu/model_serving/ci_cd/production_server/post-receive
       dest: /home/appuser/jump/hooks/post-receive

   - name: change permissions
     command: chmod +x /home/appuser/jump/hooks/post-receive

   - name: Install Docker  
     apt: pkg=docker-ce state=present update_cache=true allow_unauthenticated=yes
     become: true

   - name: Download docker-compose 
     become: yes
     get_url:        
      url: "https://github.com/docker/compose/releases/download/1.24.0/docker-compose-{{ansible_system}}-{{ansible_architecture}}"
      dest: /usr/local/bin/docker-compose
      mode: +x  

   - name: Building containers
     become: true
     shell: docker build .
     args: 
      chdir: /model_serving/ci_cd/production_server

   - name: Running containers
     become: true
     shell: docker-compose up -d 
     args: 
      chdir: /model_serving/ci_cd/production_server 

- hosts: devserver
  
  vars_files:
   - setup_var.yml

  tasks:
   - name: Extra packages
     apt: pkg=python3-pip state=latest update_cache=true  
     become: true

   - name: apt update
     apt: update_cache=yes upgrade=dist
     become: true

   - name: Install ML packages
     become: true
     pip: 
      name: pandas, numpy, scikit-learn

   - name: Create folder
     file:
       path: /home/appuser/jump
       state: directory

   - name: Create empty git repo
     command: chdir=/home/appuser/jump git init

   - name: Connect dev to prod server
     command: chdir=/home/appuser/jump git remote add production appuser@192.168.2.107:/home/appuser/jump
