version: "3"
services:
  web:
    image: resadocker/web_image:v0
    restart: always
    ports:
      - "5100:5100"
    depends_on:
      - rabbit
    volumes:
      - .:/app
  rabbit:
    hostname: rabbit
    image: rabbitmq:management
    environment:
      - RABBITMQ_DEFAULT_USER=rabbitmq
      - RABBITMQ_DEFAULT_PASS=rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
  worker_1:
    image: resadocker/workers:v0
    hostname: worker_1
    deploy:
     replicas: 2
    entrypoint: celery
    command: -A workerA worker --concurrency=12 --loglevel=debug
    volumes:
      - .:/app
    links:
      - rabbit
    depends_on:
      - rabbit
~                